version: '3'

services:
  web:
    restart: always
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    entrypoint: sh docker-entrypoint.sh
    volumes:
      - ./web:/usr/src/app
      - static-files:/usr/src/app/static
    ports:
      - "8000"
    depends_on:
      - postgres
    links:
      - postgres:postgres

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static-files:/usr/src/app/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres
    ports:
      - "5423:5423"


volumes:
  static-files:

