version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5423:5423"
  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - /usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
